name: "Build and Publish LogicTools"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "logictools V-0.1.3"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Fetch only the latest commit

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --timeout=60 --no-cache-dir build twine

      - name: Extract version number
        id: get_version
        run: |
          VERSION=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "##[set-output name=version;]$VERSION"

      - name: Rename job dynamically
        run: echo "Build logictools v${{ env.VERSION }}"

      - name: Build package
        run: python -m build --no-isolation  # Uses system dependencies to speed up build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload --non-interactive dist/*
